FROM ubuntu:26.04

RUN apt-get update && \
    apt-get install -y ca-certificates curl build-essential git xz-utils && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


COPY nscacert.pem /usr/local/share/ca-certificates/
RUN update-ca-certificates

# copy the helper script
# COPY install-certs.sh /tmp/install-certs.sh
# RUN chmod +x /tmp/install-certs.sh

# # run it
# RUN /tmp/install-certs.sh

# Download and install zig
RUN curl -Lk https://ziglang.org/download/0.15.2/zig-x86_64-linux-0.15.2.tar.xz -o /tmp/zig.tar.xz \
    && tar -xJf /tmp/zig.tar.xz -C /usr/local --strip-components=1 \
    && ln -s /usr/local/zig /usr/local/bin/zig \
    && rm /tmp/zig.tar.xz

WORKDIR /app

# Clone doom
RUN git clone https://github.com/cryptocode/terminal-doom.git

WORKDIR /app/terminal-doom

# RUN sed -i 's/\.name = \.terminaldoom,/.name = "terminal-doom",/' build.zig.zon

RUN zig build -Doptimize=ReleaseFast

CMD ["zig-out/bin/terminal-doom"]

# docker build -t terminal-doom .   
# docker scout quickview terminal-doom  
# docker scout recommendations local://terminal-doom:latest
# What's next:
#     View vulnerabilities → docker scout cves terminal-doom
#     View base image update recommendations → docker scout recommendations terminal-doom
#     Include policy results in your quickview by supplying an organization → docker scout quickview terminal-doom --org <organization>


